### ISSUE TITLE
flight: send new message to Flight when node is ready

### ISSUE THREAD

**Issue by mjtko** [alces-software/clusterware-handlers#15]
The configuration data will additionally contain a `flight` section under `instance`, e.g.:

```
write_files:
-   content: |
      cluster:
        uuid: '7b4249e8-637a-11e5-a343-7831c1c0e63c'
        token: ‘nwly-IrPU0qMLJRkcM_fzXo2np2tAVvlZNM=’
        role: 'master'
        service_url: https://flight.alces-software.com
      instance:
        flight:
          uuid: f1ce5b01-fec5-4e9d-b7bb-78e227faf7d1
```

The "Flight instance UUID" should be sent as of the `node-started` event and look something like:

```
PATCH /cluster-nodes/${cw_FLIGHT_CLUSTER_NODE_uuid}

{
    "data": {
        "type": "clusterNodes",
        "id": "${cw_FLIGHT_CLUSTER_NODE_uuid}",
        "attributes": {
            "status": "running"
        }
    }
}
```
