### ISSUE TITLE
cluster-gridware: handle deferred configuration

### ISSUE THREAD

**Issue by mjtko** [alces-software/clusterware-handlers#16]

**Comment by mjtko** [comment]
Defer configuration of gridware tree by specifying:

```
cluster:
  […]
  gridware:
    trigger: delayed
```

Trigger initialization (and slave configuration) by triggering an event:

```
/opt/clusterware/libexec/share/trigger-event --local gridware-initialize
```

This can be done after big disk/volume is formatted/mounted etc.
